language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hemant/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hemant/docker-react npm run test -- --coverage