language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hem/frontend -f Dockerfile.dev .

script:
  - npm -v
  - docker run -e CI=true hem/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-886125676109"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY