language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hemant/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hemant/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-886125676109"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY